### ISSUE TITLE
Error on deploy 

### ISSUE THREAD

**Issue by infominer33** [dumaurier/pwa_jekyll#14]
**Describe the bug**

`Error running command: Build script returned non-zero exit code: 127`

and

`Error running command: Build script returned non-zero exit code: 134`

**To Reproduce**

I click fork to netlify, enable identity and git gateway (at first I took a few extra steps trying to move to to an organization)

**Additional context**

I did some searching around and found this thread seems like it could b related:

https://github.com/netlify/netlify-statuskit/issues/57

Relevant Link:

https://www.netlify.com/blog/2019/03/14/a-more-flexible-build-architecture-with-updated-linux/

Thank You!

**Comment by dumaurier** [comment]
I'll look into today and get back to you soon.

**Comment by dumaurier** [comment]
@infominer33 There was a dependency issue in the package.json file. If you use the 'Deploy to Netlify' button it will now work correctly. 

If you want to use the existing deploy you created you can fix it by changing the build image used on  Netlify by following the instruction here: https://www.netlify.com/docs/build-settings/#build-image-selection

**Comment by infominer33** [comment]
Yay!!! and a little time before the summit to see about setting something up :)
